/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
  backendSidebar: [
    {
      type: 'autogenerated',
      dirName: 'roadmaps/backend', // Generate sidebar slice from docs/api
    }
  ],
  computerScienceSidebar: [
    {
      type: 'autogenerated',
      dirName: 'roadmaps/computer-science', // Generate sidebar slice from docs/api
    }
  ],
  frontendSidebar: [
    {
      type: 'autogenerated',
      dirName: 'roadmaps/frontend', // Generate sidebar slice from docs/api
    }
  ],
  fullStackSidebar: [
    {
      type: 'autogenerated',
      dirName: 'roadmaps/full-stack', // Generate sidebar slice from docs/api
    }
  ],
  javascriptSidebar: [
    {
      type: 'autogenerated',
      dirName: 'roadmaps/javascript', // Generate sidebar slice from docs/api
    }
  ],
  nodejsSidebar: [
    {
      type: 'autogenerated',
      dirName: 'roadmaps/nodejs', // Generate sidebar slice from docs/api
    }
  ],
};

module.exports = sidebars;
