/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
  angularSidebar: [
    {
      type: 'autogenerated',
      dirName: 'roadmaps/angular',
    }
  ],
  backendSidebar: [
    {
      type: 'autogenerated',
      dirName: 'roadmaps/backend',
    }
  ],
  computerScienceSidebar: [
    {
      type: 'autogenerated',
      dirName: 'roadmaps/computer-science',
    }
  ],
  cppSidebar: [
    {
      type: 'autogenerated',
      dirName: 'roadmaps/cpp',
    }
  ],
  cyberSecuritySidebar: [
    {
      type: 'autogenerated',
      dirName: 'roadmaps/cyber-security',
    }
  ],
  designSystemSidebar: [
    {
      type: 'autogenerated',
      dirName: 'roadmaps/design-system',
    }
  ],
  devopsSidebar: [
    {
      type: 'autogenerated',
      dirName: 'roadmaps/devops',
    }
  ],
  dockerSidebar: [
    {
      type: 'autogenerated',
      dirName: 'roadmaps/docker',
    }
  ],
  flutterSidebar: [
    {
      type: 'autogenerated',
      dirName: 'roadmaps/flutter',
    }
  ],
  frontendSidebar: [
    {
      type: 'autogenerated',
      dirName: 'roadmaps/frontend',
    }
  ],
  fullStackSidebar: [
    {
      type: 'autogenerated',
      dirName: 'roadmaps/full-stack',
    }
  ],
  golangSidebar: [
    {
      type: 'autogenerated',
      dirName: 'roadmaps/golang',
    }
  ],
  graphqlSidebar: [
    {
      type: 'autogenerated',
      dirName: 'roadmaps/graphql',
    }
  ],
  javaSidebar: [
    {
      type: 'autogenerated',
      dirName: 'roadmaps/java',
    }
  ],
  javascriptSidebar: [
    {
      type: 'autogenerated',
      dirName: 'roadmaps/javascript',
    }
  ],
  kubernetesSidebar: [
    {
      type: 'autogenerated',
      dirName: 'roadmaps/kubernetes',
    }
  ],
  mongodbSidebar: [
    {
      type: 'autogenerated',
      dirName: 'roadmaps/mongodb',
    }
  ],
  nodejsSidebar: [
    {
      type: 'autogenerated',
      dirName: 'roadmaps/nodejs',
    }
  ],
  postgresqlDbaSidebar: [
    {
      type: 'autogenerated',
      dirName: 'roadmaps/postgresql-dba',
    }
  ],
  promptEngineeringSidebar: [
    {
      type: 'autogenerated',
      dirName: 'roadmaps/prompt-engineering',
    }
  ],
  pythonSidebar: [
    {
      type: 'autogenerated',
      dirName: 'roadmaps/python',
    }
  ],
  qaSidebar: [
    {
      type: 'autogenerated',
      dirName: 'roadmaps/qa',
    }
  ],
  reactSidebar: [
    {
      type: 'autogenerated',
      dirName: 'roadmaps/react',
    }
  ],
  softwareArchitectSidebar: [
    {
      type: 'autogenerated',
      dirName: 'roadmaps/software-architect',
    }
  ],
  softwareDesignArchitectureSidebar: [
    {
      type: 'autogenerated',
      dirName: 'roadmaps/software-design-architecture',
    }
  ],
  springBootSidebar: [
    {
      type: 'autogenerated',
      dirName: 'roadmaps/spring-boot',
    }
  ],
  sqlSidebar: [
    {
      type: 'autogenerated',
      dirName: 'roadmaps/sql',
    }
  ],
  systemDesignSidebar: [
    {
      type: 'autogenerated',
      dirName: 'roadmaps/system-design',
    }
  ],
  typescriptSidebar: [
    {
      type: 'autogenerated',
      dirName: 'roadmaps/typescript',
    }
  ],
  uxDesignSidebar: [
    {
      type: 'autogenerated',
      dirName: 'roadmaps/ux-design',
    }
  ],
  vueSidebar: [
    {
      type: 'autogenerated',
      dirName: 'roadmaps/vue',
    }
  ],
};

module.exports = sidebars;
